=== fiboa/specification/geojson/schema/Feature.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://geojson.org/schema/Feature.json",
  "title": "GeoJSON Feature",
  "type": "object",
  "required": [
    "type",
    "properties",
    "geometry"
  ],
  "properties": {
    "type": {
      "type": "string",
      "enum": [
        "Feature"
      ]
    },
    "id": {
      "oneOf": [
        {
          "type": "number"
        },
        {
          "type": "string"
        }
      ]
    },
    "properties": {
      "oneOf": [
        {
          "type": "null"
        },
        {
          "type": "object"
        }
      ]
    },
    "geometry": {
      "$ref": "https://geojson.org/schema/Geometry.json"
    },
    "bbox": {
      "type": "array",
      "minItems": 4,
      "items": {
        "type": "number"
      }
    }
  }
}

=== fiboa/specification/geojson/examples/example.json
{
  "id": "1234",
  "type": "Feature",
  "bbox": [
    172.91173669923782,
    1.3438851951615003,
    172.95469614953714,
    1.3690476620161975
  ],
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [
        [
          172.91173669923782,
          1.3438851951615003
        ],
        [
          172.95469614953714,
          1.3438851951615003
        ],
        [
          172.95469614953714,
          1.3690476620161975
        ],
        [
          172.91173669923782,
          1.3690476620161975
        ],
        [
          172.91173669923782,
          1.3438851951615003
        ]
      ]
    ]
  },
  "properties": {
    "determination_datetime": "2020-01-01T00:00:00Z"
  }
}

=== fiboa/specification/geojson/examples/individual-features/12324.json
{
  "id": "12324",
  "type": "Feature",
  "properties": {
    "schemas": {
      "example": [
        "https://fiboa.github.io/specification/v0.3.0/schema.yaml",
        "https://fiboa.github.io/flik-extension/v0.1.0/schema.yaml"
      ]
    },
    "collection": "example",
    "flik": "DENWLI0542130247",
    "determination_datetime": "2005-02-28T00:00:00Z",
    "nutz_code": "A",
    "nutz_txt": "Ackerland",
    "area": 1.6311
  },
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [
        [7.8752433, 51.7469574],
        [7.8754156, 51.7486557],
        [7.8755951, 51.7486575],
        [7.8757271, 51.7486476],
        [7.8758657, 51.7486117],
        [7.8761609, 51.7485365],
        [7.8762749, 51.7485265],
        [7.8766462, 51.7485226],
        [7.8766691, 51.7475958],
        [7.8766832, 51.7470291],
        [7.8752433, 51.7469574]
      ]
    ]
  }
}
